# Base compartilhado por todos os ambientes.
# Mesclado antes dos overlays de ambiente e de projeto.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15-alpine"

nameOverride: ""
fullnameOverride: ""

postgresql:
  username: postgres
  password: postgres
  initScript: false
  initScriptSql: ""

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  exec:
    command:
      - /bin/sh
      - -c
      - pg_isready -U postgres
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  exec:
    command:
      - /bin/sh
      - -c
      - pg_isready -U postgres
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

podSecurityContext:
  fsGroup: 999

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

nodeSelector: {}
tolerations: []
affinity: {}
